spring:
  datasource:
    url: jdbc:mysql://localhost:32777/asses
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        generate_statistics: true

logging:
  level:
   # root: DEBUG
    org.acme.micros.webapp: DEBUG
    org.hibernate.SQL: DEBUG
   # org.springframework.orm.jpa: DEBUG
   # org.springframework.jdbc.core: DEBUG
   # com.zaxxer.hikari.HikariConfig: DEBUG
   # org.springframework.transaction: DEBUG